name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'HellRaiser_Frontend/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Frontend Directory
        id: find-frontend
        run: |
          if [ -d "HellRaiser_Frontend" ]; then
            echo "FRONTEND_DIR=HellRaiser_Frontend" >> $GITHUB_OUTPUT
          elif [ -d "hellraiser-frontend" ]; then
            echo "FRONTEND_DIR=hellraiser-frontend" >> $GITHUB_OUTPUT
          elif [ -d "frontend" ]; then
            echo "FRONTEND_DIR=frontend" >> $GITHUB_OUTPUT
          else
            echo "Available directories:"
            ls -la
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '${{ steps.find-frontend.outputs.FRONTEND_DIR }}/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ steps.find-frontend.outputs.FRONTEND_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ steps.find-frontend.outputs.FRONTEND_DIR }}
        env:
          VITE_API_URL: https://hellraiser-backend.onrender.com/api

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '${{ steps.find-frontend.outputs.FRONTEND_DIR }}/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

